const poemsData = [
    {
        "id": 1,
        "title": "Be Unapologetically Authentic",
        "description": "A heartfelt reflection on self-love, growth, and embracing one's true self without fear of judgment.",
        "author": "Bhavti",
        "content": "This feeling that holds me right now, is too precious to be left unwritten. Yes, it is love. I am falling in love, all over again. With whom? With myself, silly! After all, I was and will always be my first love na. And the amount of growth I have been noticing in myself lately, it is what I once dreamt of.\n\nHaving been the little girl that I was—timid, hesitant, insecure, and whatnot—it took a lot of fake confidence and stick-on smiles to hide it all. But now? I see it coming naturally (fingers crossed). I’m no longer that bothered by opinions, judgments, or even the loss of people.\n\nI always loved to talk, been the loud little girl who was told to ‘Shut up,’ ‘Talk less,’ ‘Don’t be loud,’ and that went in deep as insecurities—an anxiety of never fitting in, of being the odd one out. And yes, I was right, I don’t fit in. I will always be too loud, too excited, too bubbly for many. But I feel loved exactly as I am, and that is what matters. I remember crying my eyes out for nights whenever someone pointed out my outspoken or hyperactive nature or physical flaws. It hardly affects me now, and I am proud of this progress.\n\nAfter all these years of suppressing my identity just to fit in, to not catch attention, to stay away from the limelight, to follow the set rules—I feel I have accepted myself now. I see myself having fun, laughing out loud, dancing, singing, acting, all for fun! This was all a dream!! A dream that I see myself living now. The dream of not being affected by gazes, not being afraid of judgment, of stepping out of societal norms.\n\nAs someone who never stepped out in public all this time, growing up into someone who can now stand for others too, I am falling in love with these changes. I hope someday everyone who has suppressed any part of their being gets to witness their growth and fall in love with themselves too.\n\nYou’ll always be judged, you’ll always be hated, but don’t let that affect you. No singer will ever judge your love for singing, no dancer will ever judge you for dancing your heart out… The only reason someone hates you is because you have something they don’t, which is courage. Don’t let anyone take that away from you, ever! Be yourself unapologetically!\n\nI don’t know if my family or this society will ever fully accept the woman that I am becoming, but my love does, my friends do, my sister does, and most importantly, I do. Even if nobody takes pride in my growth, in my journey—I do. The little girl in me does. I am proud of my growth.\n\nAll I hope is the same for everyone. This is a reminder to look back upon your journey and see how far you have come. Take pride in it. Love yourself a little more every day.\n\nBe Unapologetically Authentic!"
      },
      
    
];
